# Generated by Django 3.2.19 on 2026-09-15 06:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_populate_existing_movies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['row', 'number', 'seat_number']},
        ),
        migrations.AddField(
            model_name='seat',
            name='lock_session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seat',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_seats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seat',
            name='locked_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('180.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='seat',
            name='tier',
            field=models.CharField(choices=[('VIP', 'VIP Recliner Pod'), ('BALCONY', 'Balcony Gold Plus'), ('GOLD', 'Gold Club Class'), ('SILVER_PLUS', 'Silver Plus'), ('SILVER', 'Silver Standard')], default='SILVER', max_length=20),
        ),
    ]
