# Generated by Django 3.2.19 on 2026-09-15 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20260915_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe')], default='RAZORPAY', max_length=20)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI / QR'), ('card', 'Credit / Debit Card'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet / FastPay')], default='upi', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Payment Cancelled'), ('REFUNDED', 'Payment Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('signature', models.CharField(blank=True, default='', max_length=255)),
                ('seat_ids', models.JSONField(blank=True, default=list)),
                ('seat_numbers', models.CharField(blank=True, default='', max_length=255)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='movies.movie')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='movies.showschedule')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='movies.theater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='movies.payment'),
        ),
    ]
